name: Linting

on: [push, pull_request]

jobs:
  ruff-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          version: '0.9.2'
          args: format --check
          src: './src'