name: release

on:
  release:
    types:
    - published  # Published through GitHub UI: https://github.com/amazon-science/synthesizrr/releases/new

jobs:
  pypi:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for Git versioning

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Hatch & Twine
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv 
        python -m uv pip install hatch twine 

    - name: Verify Version from Git Tag
      run: hatch version

    - name: Build Package
      run: hatch build

    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: twine upload --repository testpypi dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --repository pypi dist/*